name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run:
        echo $CR_PAT | docker login ghcr.io -u thebadwolf79 --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dockerfile:latest$(date +%s)
    
    - name: Docker Push
      run: docker push dockerfile:latest
